version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '6'
    ports:
      - "80:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev